src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 * @UniqueEntity("Name")
 * @Vich\Uploadable
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $Name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Series", inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Series;

    /**
     * @ORM\Column(type="integer")
     */
    private $OrderInSeries;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $AmazonLink;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     */
    private $imageName;

    /**
     * @Vich\UploadableField(mapping="books", fileNameProperty="imageName", size="imageSize")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @var int|null
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Excerpt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="Book")
     */
    private $Reviews;

    public function __construct()
    {
        $this->Reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSeries(): ?Series
    {
        return $this->Series;
    }

    public function setSeries(?Series $Series): self
    {
        $this->Series = $Series;

        return $this;
    }

    public function getOrderInSeries(): ?int
    {
        return $this->OrderInSeries;
    }

    public function setOrderInSeries(int $OrderInSeries): self
    {
        $this->OrderInSeries = $OrderInSeries;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAmazonLink(): ?string
    {
        return $this->AmazonLink;
    }

    public function setAmazonLink(string $AmazonLink): self
    {
        $this->AmazonLink = $AmazonLink;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile($imageFile): self
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function setImageSize(?int $imageSize): self
    {
        $this->imageSize = $imageSize;

        return $this;
    }

    public function getExcerpt(): ?string
    {
        return $this->Excerpt;
    }

    public function setExcerpt(?string $Excerpt): self
    {
        $this->Excerpt = $Excerpt;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->Reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->Reviews->contains($review)) {
            $this->Reviews[] = $review;
            $review->setBook($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->Reviews->contains($review)) {
            $this->Reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getBook() === $this) {
                $review->setBook(null);
            }
        }

        return $this;
    }
}

src/Entity/Review.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReviewRepository")
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Hyperlink;

    /**
     * @ORM\Column(type="text")
     */
    private $Review;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Book", inversedBy="Reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Book;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getHyperlink(): ?string
    {
        return $this->Hyperlink;
    }

    public function setHyperlink(string $Hyperlink): self
    {
        $this->Hyperlink = $Hyperlink;

        return $this;
    }

    public function getReview(): ?string
    {
        return $this->Review;
    }

    public function setReview(string $Review): self
    {
        $this->Review = $Review;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->Book;
    }

    public function setBook(?Book $Book): self
    {
        $this->Book = $Book;

        return $this;
    }
}

src/Controller/StoriesController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\Series;
use App\Entity\Updates;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class StoriesController extends AbstractController
{
    /**
     * @Route("/stories", name="app_stories")
     */
    public function index(EntityManagerInterface $em)
    {
        $series = $em->getRepository(Series::class)->findAllSortedPriority();
        $updates = $em->getRepository(Updates::class)->findAllSortedPriority();
        return $this->render('stories/books.html.twig', [
            'controller_name' => 'StoriesController',
            'series' => $series,
            'updates' => $updates,
        ]);
    }
    /**
     * @Route("/stories/book/{id}", name="app_story")
     */
    public function storyPage(EntityManagerInterface $em,$id)
    {
        $book = $em->getRepository(Book::class)->find($id);
        return $this->render('stories/book.html.twig', [
            'book' => $book,
        ]);
    }
    /**
     * @Route("/stories/series/{id}", name="app_serial")
     */
    public function seriesPage(EntityManagerInterface $em,$id)
    {
        $serial = $em->getRepository(Series::class)->find($id);
        return $this->render('stories/serial.html.twig', [
            'serial' => $serial,
        ]);
    }
}

templates/stories/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books{% endblock %}
{% block body %}
    <h2>{{ book.name }} (#{{ book.orderInSeries }} in {{ book.series.name }})</h2>
    <a href="{{ book.AmazonLink }}">
        <img src="{{ vich_uploader_asset(book,'imageFile') }}" class="w-25 float-left mr-1">
    </a>
    <p>{{ book.description|change_return_to_break|raw }}</p>
    {% if book.reviews|length > 0 %}
        <h3>Featured Reviews</h3>
    {% endif %}
    {% for review in book.reviews %}
    <h4><a href="{{ review.hyperlink }}">{{ review.name }}</a></h4>
    <p>{{ review.review|change_return_to_break|raw }}</p>
    {% endfor %}
{% endblock %}

templates/stories/books.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('/style/StoriesV2.css') }}">
{% endblock %}
{% block body_indentation %}
    {% if updates|length > 0 %}
        <div class="inc-bg-snow emphasis-paragraph">
            {% for update in updates %}
                <div class="pl-4 pt-3 pb-2 story-emphatic"{% if update.fontSize or update.fontColor%} style="{% if update.fontSize %}font-size:{{ update.fontSize }}em;{% endif %}{% if update.fontColor %}color:{{ update.fontColor }};{% endif %}{% endif %}"><strong>{% if update.book %}<a class="" href="{{ update.book.amazonLink }}"{% if update.fontColor %} style="color:{{ update.fontColor }};"{% endif %}>{{ update.book.name }}</a> {% endif %}{{ update.description }}{% if update.closeDescription %} {% if update.closeLink %}<a class="" href="{{ update.closeLink }}"{% if update.fontColor %} style="color:{{ update.fontColor }};"{% endif %}>{% endif %}{{ update.closeDescription }}{% if update.closeLink %}</a>{% endif %}{% endif %}</strong></div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="inc-indentation mt-2">
        <div class="d-flex inc-flex-orientation">
            <div class="p-1">
                <h1>Novels and Short Stories</h1>
                <p></p>
                <h3>Here are quick links to information about each of my book series.</h3>
                <div class="d-flex flex-row flex-wrap">
                    {% for serial in series %}
                        <a href="{{ path('app_serial',{'id':serial.id}) }}">
                            <button class="btn inc-bg-ldahners7 m-2">{{ serial.name }}</button>
                        </a>
                    {% endfor %}
                </div>
                <p></p>
                <h3>Below are the covers of all of my books</h3>
                <p>(Click on a cover to go to the store or the about button for more information)</p>
            </div>
        </div>
        <div class="d-flex flex-column">
        {% for serial in series %}
            <div class="d=flex flex-column">
                <p></p>
                <h4>{{ serial.name }} <a href="{{ path('app_serial',{'id':serial.id}) }}" class="ml-2"><btn class="btn inc-bg-ldahners7 text-dark">Review of Series</btn></a></h4>
                <p>{{ serial.description }}</p>
                <div class="inc-flex-orientation">
                    <div class="books d-flex flex-wrap">
                        {% for book in serial.books|sort((a, b) => a.OrderInSeries <=> b.OrderInSeries) %}
                            <div class="inc-book-image">
                                <a href="{{ book.AmazonLink }}">
                                    <img src="{{ vich_uploader_asset(book,'imageFile') }}">
                                </a>
                                <a href="{{ path('app_story',{'id':book.id}) }}">
                                    <button class="btn inc-bg-ldahners7 mx-auto d-block mt-2">About</button>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="merchandise">
                        {% for merchandise in serial.merchandise %}
                            <div class="merch-item">
                                <h4>{{ merchandise.name }}</h4>
                                <p>{{ merchandise.description|change_return_to_break|raw }}</p>
                                <a href="{{ merchandise.link }}">
                                    <div class="inc-book-image">
                                        <img src="{{ vich_uploader_asset(merchandise,'imageFile') }}">
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                        <div class="inc-flex-grow"></div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/stories/serial.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ serial.name }}{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('/style/StoriesV2.css') }}">
{% endblock %}
{% block body %}
    <div class="d=flex flex-column">
        <h4>{{ serial.name }}</h4>
        <p>{{ serial.description }}</p>
        <div class="featured-reviews">
            <h5>Featured Reviews</h5>
            {% for review in serial.seriesReviews %}
                <div>
                    <h3><a href="{{ review.hyperlink }}">{{ review.name }}</a></h3>
                    <p>{{ review.review|change_return_to_break|raw }}</p>
                </div>
            {% endfor %}
        </div>
        <div class="inc-flex-orientation">
            <div class="books d-flex flex-wrap">
                {% for book in serial.books|sort((a, b) => a.OrderInSeries <=> b.OrderInSeries) %}
                    <div class="inc-book-image">
                        <a href="{{ book.AmazonLink }}">
                            <img src="{{ vich_uploader_asset(book,'imageFile') }}">
                        </a>
                        <a href="{{ path('app_story',{'id':book.id}) }}">
                            <button class="btn inc-bg-ldahners7 mx-auto d-block mt-2">About</button>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="merchandise">
                {% for merchandise in serial.merchandise %}
                    <div class="merch-item">
                        <h4>{{ merchandise.name }}</h4>
                        <p>{{ merchandise.description|change_return_to_break|raw }}</p>
                        <a href="{{ merchandise.link }}">
                            <div class="inc-book-image">
                                <img src="{{ vich_uploader_asset(merchandise,'imageFile') }}">
                            </div>
                        </a>
                    </div>
                {% endfor %}
                <div class="inc-flex-grow"></div>
            </div>
        </div>
    </div>
{% endblock %}