src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 * @UniqueEntity("Name")
 * @Vich\Uploadable
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $Name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Series", inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Series;

    /**
     * @ORM\Column(type="integer")
     */
    private $OrderInSeries;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $AmazonLink;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     */
    private $imageName;

    /**
     * @Vich\UploadableField(mapping="books", fileNameProperty="imageName", size="imageSize")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @var int|null
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Excerpt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="Book")
     */
    private $Reviews;

    public function __construct()
    {
        $this->Reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getSeries(): ?Series
    {
        return $this->Series;
    }

    public function setSeries(?Series $Series): self
    {
        $this->Series = $Series;

        return $this;
    }

    public function getOrderInSeries(): ?int
    {
        return $this->OrderInSeries;
    }

    public function setOrderInSeries(int $OrderInSeries): self
    {
        $this->OrderInSeries = $OrderInSeries;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAmazonLink(): ?string
    {
        return $this->AmazonLink;
    }

    public function setAmazonLink(string $AmazonLink): self
    {
        $this->AmazonLink = $AmazonLink;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile($imageFile): self
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function setImageSize(?int $imageSize): self
    {
        $this->imageSize = $imageSize;

        return $this;
    }

    public function getExcerpt(): ?string
    {
        return $this->Excerpt;
    }

    public function setExcerpt(?string $Excerpt): self
    {
        $this->Excerpt = $Excerpt;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->Reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->Reviews->contains($review)) {
            $this->Reviews[] = $review;
            $review->setBook($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->Reviews->contains($review)) {
            $this->Reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getBook() === $this) {
                $review->setBook(null);
            }
        }

        return $this;
    }
}

src/Entity/Review.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReviewRepository")
 */
class Review
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Hyperlink;

    /**
     * @ORM\Column(type="text")
     */
    private $Review;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Book", inversedBy="Reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Book;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getHyperlink(): ?string
    {
        return $this->Hyperlink;
    }

    public function setHyperlink(string $Hyperlink): self
    {
        $this->Hyperlink = $Hyperlink;

        return $this;
    }

    public function getReview(): ?string
    {
        return $this->Review;
    }

    public function setReview(string $Review): self
    {
        $this->Review = $Review;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->Book;
    }

    public function setBook(?Book $Book): self
    {
        $this->Book = $Book;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html id="inc-top-html" class="inc-top-html">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="shortcut icon" href="{{asset('/assets/images/0-simple-donsaii-tiny.jpg')}}" type="image/x-icon">
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('/style/ldahnersMain.css') }}">
        {% endblock %}
{#        <script src="{{ asset('packs/js/cookies.js') }}"></script>#}
{#        <script>#}
{#            var incarnateDomain = 'ldahners.incarnategamingllc.com';#}
{#        </script>#}
        <script src="{{ asset('packs/js/hooks.js') }}"></script>
        <script src="{{asset('packs/js/ldahnersIncarnateReference.js')}}"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="d-flex flex-column">
        <div class="inc-nav-body inc-text-ldahners4 inc-bg-ldahners2-dark">
            <div class="inc-nav-flex-holder"></div>
            <div class="inc-body d-flex flex-column">
                <div class="inc-flex-grow">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}
                {% for message in app.flashes('failure') %}
                    <div class="alert alert-danger">
                        {{ message }}
                    </div>
                {% endfor %}
                {% block body_indentation %}
                    <div class="inc-indentation mt-2">
                        {% block body %}{% endblock %}
                    </div>
                {% endblock %}
                </div>
                <footer class="page-footer font-small inc-banners inc-bg-ldahners4-dark">
                    <div class="footer-copyright text-center py-3 inc-text-light">
                        © 2020 <a class="inc-text-light" href="https://www.incarnategamingllc.com/hire/">Incarnate Gaming LLC</a>
                    </div>
                </footer>
            </div>
        </div>
        <nav class="navbar inc-sticky-header inc-banners align-content-start inc-bg-ldahners4-dark" id="navbar">
            <button class="navbar-toggler text-dark mr-auto inc-button-color inc-bg-ldahners7" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a id="incarnate-logo" class="navbar-brand inc-text-light ml-2" href="/">Laury Dahners<img src="{{ asset('/assets/images/0-simple-donsaii-tiny.jpg') }}" class="ml-3 mr-1"></a>
            <div class="collapse navbar-collapse overflow-auto" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_home')|index_stripper }}'">Home</button>
                    </li>
                    <li class="nav-item">
                        <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_stories')|index_stripper }}'">Novels & Short Stories</button>
                    </li>
                    {%  if is_granted('ROLE_ADMIN') %}
                        <li class="nav-item">
                            <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_admin_index')|index_stripper }}'">Admin Functions</button>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_songs_vocal')|index_stripper }}'">Songs</button>
                    </li>
                    <li class="nav-item">
                        <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_songs_instrumental')|index_stripper }}'">Instrumental Music</button>
                    </li>
                    <li class="nav-item">
                        <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_art_digital')|index_stripper }}'">Digital Art</button>
                    </li>
                    <li class="nav-item">
                        <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_art_physical')|index_stripper }}'">Art</button>
                    </li>
                    <li class="nav-item">
                        <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_charity')|index_stripper }}'">Charity Surgery</button>
                    </li>
                    <li class="nav-item">
                        <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_professional')|index_stripper }}'">Orthopedic</button>
                    </li>
                    {#                    <li class="nav-item">#}
                    {#                        <button class="btn btn-primary m-2" id="contentDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Content</button>#}
                    {#                        <div class="dropdown-menu overflow-auto" aria-labelledby="contentDropdown">#}
                    {#                            <a class="dropdown-item text-primary" href="{{ path('inc_backgrounds')|index_stripper }}">Backgrounds</a>#}
                    {#                        </div>#}
                    {#                    </li>#}
                    <button class="btn m-2 inc-button-color inc-bg-ldahners7" id="topButton" type="button" aria-label="Navigate to Top">Top</button>
                    {% block backButton %}{% endblock %}
                </ul>
            </div>
            {% block additionalLogos %}
                <img src="{{ asset('/assets/images/0-simple-help-tiny.jpg') }}" class="mr-1 inc-closing-logo">
            {% endblock %}
            {%  if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                <list class="inc-nav-final-buttons">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <button class="btn m-2 inc-button-color inc-bg-ldahners7" onclick="window.location.href='{{ path('app_account_changePassword')|index_stripper }}'">Change Password</button>
                        </li>
                    </ul>
                </list>
            {% endif %}
        </nav>
        {% block javascripts %}
{#            <script>#}
{#                var IncarnateAnalyticsTag = 'UA-155417623-1';#}
{#            </script>#}
            <script src="{{asset('packs/js/ldahnersNavFunctionsV2.js')}}"></script>
            <script src="{{ asset('packs/js/orientation.js') }}"></script>
{#            <script src="{{ asset('packs/js/analytics.js') }}"></script>#}
            <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{#            {% block policyAccept %}<script src="{{ asset('packs/js/policyAccept.js') }}"></script>{% endblock %}#}
{#            <script src="{{ asset('packs/js/colorTryer.js') }}"></script>#}
{#            <script>#}
{#                IncarnateColorTryer.build('inc-nav-body','color','Page Text Color');#}
{#                IncarnateColorTryer.build('inc-nav-body','background-color','Page Background Color');#}
{#                IncarnateColorTryer.build('inc-banners','background-color','Header Footer Background Color');#}
{#                IncarnateColorTryer.build('inc-button-color','background-color','Button Color');#}
{#            </script>#}
        {% endblock %}
    </body>
</html>

templates/home.html.twig
{%  extends 'base.html.twig' %}
{% block title %}Laury Dahners{% endblock %}
{% block body_indentation %}
    {% if updates|length > 0 %}
        <div class="inc-bg-snow emphasis-paragraph dark-background">
            {% for update in updates %}
                {%  if update.book %}
                <div class="pl-4 pt-3 pb-2 story-emphatic"{% if update.fontSize or update.fontColor%} style="{% if update.fontSize %}font-size:{{ update.fontSize }}em;{% endif %}{% if update.fontColor %}color:{{ update.fontColor }};{% endif %}{% endif %}"><strong>{% if update.book %}<a class="" href="{{ update.book.amazonLink }}"{% if update.fontColor %} style="color:{{ update.fontColor }};"{% endif %}>{{ update.book.name }}</a> {% endif %}{{ update.description }}{% if update.closeDescription %} {% if update.closeLink %}<a class="" href="{{ update.closeLink }}"{% if update.fontColor %} style="color:{{ update.fontColor }};"{% endif %}>{% endif %}{{ update.closeDescription }}{% if update.closeLink %}</a>{% endif %}{% endif %}</strong></div>
                {%  endif %}
            {% endfor %}
        </div>
    {% endif %}
    <div class="inc-indentation mt-2">
        <h1 class="text-center">Laury Dahners</h1>
        <div class="row">
            <div class="col-md-8">
                <img src="/assets/images/Laury sepia.jpg" class="mx-auto d-block img-fluid">
            </div>
            <div class="col-md-3 dark-background">
                <p>Laury Dahners lives in Chapel Hill, North Carolina and enjoys composing and recording music as well as painting. Recently he's become interested in writing science fiction. For a day job he worked (retired now) as an orthopedic surgeon who taught at the University of North Carolina Medical School, Department of Orthopaedics. Thanks to his daughter <a href="http://www.elene.dahners.com/">Elene Dahners</a> for teaching him how to build his first website! And to Philip Lawrence of <a href="https://www.incarnategamingllc.com/hire/">Incarnate Gaming</a> for building this updated version!</p>
            </div>
        </div>
    </div>
{% endblock %}